adduct_num: 10
aug: null
batch_size: 128
checkpoint_dir: ./Attention_Full_A0/models
checkpoint_every: 10
checkpoint_root: ./Attention_Full_A0
checkpoints_folder: ./Attention_Full_A0
d_dropout: 0.0
data_root: data/FD_in-house
dataset_name: FD_in-house
dataset_names:
- valid
- test
n_embd: 768
n_layer: 12
n_head: 12
device: cuda
dropout: 0.0
ecfp_num: 1024
from_scratch: false
lr_multiplier: 1
lr_start: 1.0e-05
max_epochs: 1000
measure_name: CCS
num_feats: 32
num_workers: 20
eval_dataset_length: null
project_name: Attention_Full_A0
seed: 12345
type: later
