adduct_num: 3
aug: null
batch_size: 64
checkpoint_dir: ./Attention_Full_M0/models
checkpoint_every: 10
checkpoint_root: ./Attention_Full_M0
checkpoints_folder: ./Attention_Full_M0
d_dropout: 0.0
data_root: data/FD_M0
dataset_name: FD_M0
dataset_names:
- valid
- test
desc_skip_connection: false
device: cuda
dims:
- 768
- 768
- 768
- 1
dropout: 0.0
ecfp_num: 1024
eval_dataset_length: null
fc_h: 512
fold: 0
from_scratch: false
lr_multiplier: 1
lr_start: 1.0e-05
max_epochs: 1000
measure_name: CCS
mode: avg
n_batch: 64
n_embd: 768
n_head: 12
n_jobs: 1
n_layer: 12
num_classes: null
num_feats: 32
num_workers: 20
project_name: Attention_Full_A0
results_dir: ./Attention_Full_A0/results
seed: 12345
seed_path: ./Pretrained MoLFormer/checkpoints/N-Step-Checkpoint_3_30000.ckpt
smiles_embedding: /dccstor/medscan7/smallmolecule/runs/ba-predictor/small-data/embeddings/protein/ba_embeddings_tanh_512_2986138_2.pt
train_dataset_length: null
type: later
