
ORINGINAL_BASE_PATH = './original_data'
RESULTS_BASE_PATH = './results'
FINAL_DATA_PATH = './datas'
# ALLCCS_PATH = [BASE_PATH + r"/AllCCS download" + rf' ({i}).csv' for i in range(43)]
ALLCCS_FINAL_PATH = [ORINGINAL_BASE_PATH + '/ALLCCS_FINAL.csv']
ALLCCS_PATH = [ORINGINAL_BASE_PATH + '/ALLCCS_ISO.csv']
ALLCCS_EXP_PATH = [ORINGINAL_BASE_PATH + '/ALLCCS_EXP.csv']
MELTIN_PATH = [ORINGINAL_BASE_PATH + '/METLIN_IMS_rmTM.csv']
Final_MELTIN_PATH = [ORINGINAL_BASE_PATH + '/MZ_ISO_METLIN.csv']